### ISSUE TITLE
Encountered this error when trying to seed...

### ISSUE THREAD

**Issue by savvytech-sg** [lwwcas/laravel-countries#1]
Hi,

Thanks for the great laravel package. I was trying it out, followed the instructions and hit an error when seeding.

![Screenshot 2021-01-11 at 9 21 44 AM](https://user-images.githubusercontent.com/72496031/104140880-ac1f8200-53ee-11eb-905e-fb646791aedb.png)

any advice?

**Comment by lwwcas** [comment]
Hi, I'm glad this package is being useful, I'm sorry for the delay in responding

Seeing how useful this package is, I'll pay much more attention to it from now on.

I will be implementing tests so that this type of error does not happen again

**Comment by lwwcas** [comment]
I can't reproduce this error exactly
Could you tell me a little about how you got to this error?

**Comment by lwwcas** [comment]
I will be closing this issue , but I would like you to open a new issue again so we can resolve everything
