### ISSUE TITLE
Appetite to switch to JSON for languages

### ISSUE THREAD

**Issue by lrljoe** [lwwcas/laravel-countries#18]
Is there any appetite to swap to JSON files for the language seeders?

This would then allow for simpler updating, or use of the Google Translation packages to swiftly add in additional translations.

**Comment by lwwcas** [comment]
hello @lrljoe 
Thank you for contributing this question,

At the moment we do not have this support in the package.

But I'll write it down here on my side, and I'll add it in the next versions.

**Comment by lrljoe** [comment]
Sounds good to me, thanks for taking it on board.

Once they're in JSON format, there are decent packages for converting them into other languages.

For complex strings it isn't particularly clean, but for lists of short strings it's fine.

You could then just have a simple install command that checks the locales available, does the conversion, and then runs the seeder, that way it'll support a wider range of languages.
