### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by lifegiro** [lwwcas/laravel-countries#23]
Is there a timeline to support installations into Laravel 11?

**Comment by khamsolt** [comment]
@lwwcas please, I need your package in a new project =)

**Comment by lwwcas** [comment]
Sorry for the delay in getting support for Laravel 11 up and running. 
I've been on the move between countries lately. 
I truly appreciate your patience, and I'm thrilled to see the community embracing the package. 

Rest assured, I'll be giving it the attention it deserves this year.

**Comment by lwwcas** [comment]
Great news! As of today, support for Laravel 11 is now available. I've just released version 3.5.0 of the package. You can check it out on GitHub at https://github.com/lwwcas/laravel-countries/releases/tag/3.5.0. Thanks for your patience and support!

**Comment by khamsolt** [comment]
Thank you, dear friend =)
