### ISSUE TITLE
"attribute [localeKey] either does not exist" error with using shouldBeStrict() in Laravel 11

### ISSUE THREAD

**Issue by lifegiro** [lwwcas/laravel-countries#27]
I added shouldBeStrict(); in order to prevent lazy Loading across my models in AppServiceProvider class.

Resulting in the following error message:

The attribute [localeKey] either does not exist or was not retrieved for model [Lwwcas\LaravelCountries\Models\Country].

it seems to be in the astronomic / laravel sub package.

Without, it works seamless in getting the countries from db            $countries = Country::_all('locale', 'de');

**Comment by lwwcas** [comment]
Thanks for your contribution @lifegiro 

Today I will take some time to update the package and release a version with this fix.

**Comment by lwwcas** [comment]
@lifegiro I'm hoping that this fix will solve whatever problem you've been encountering.

Let me know if you have the same problem please

You can update your package version or follow the link to find the new version
https://github.com/lwwcas/laravel-countries/releases/tag/3.5.2

**Comment by lifegiro** [comment]
It came across again with a different error note. To void this error, I have moved the Livewire request from  mont() function to render() which solved it. Now tit works with having enforced strict to avoid Lazy Loading (n+1). Thank you for this amazing package to simplify developer's life and globalize locations.
