### ISSUE TITLE
Countries missing?

### ISSUE THREAD

**Issue by martin-ro** [lwwcas/laravel-countries#4]
Can't seem to find the Philippines for example.

**Comment by lwwcas** [comment]
Hello Martin,
I can only thank you for finding this bug

I fixed it, and listed in this release (3.3.1) how to correctly update,
https://github.com/lwwcas/laravel-countries/releases/tag/3.3.1

But I'll put the steps here to help you

Please test before sending to production, and don't forget to backup before

1. Run `php artisan make:seeder PhilippinesData`
2. Paste this code in the seed that was created 
`$this->call(\Lwwcas\LaravelCountries\Database\Seeders\fix\PhilippinesTranslatesUpdatedSeeder::class);`
3. Run the seed that was created with the command `php artisan db:seed --class=PhilippinesData`
4. Delete **PhilippinesData.php** file

The changes will create in your database the Filipina country and its translations, in respective tables.


**Thank you very much for the support**
