### ISSUE TITLE
Support Laravel 9

### ISSUE THREAD

**Issue by ahaneef29** [lwwcas/laravel-countries#5]
Looking for Support, Laravel 9

**Comment by vadimwe** [comment]
+1

**Comment by vadimwe** [comment]
@lwwcas can you update package please

**Comment by zerossB** [comment]
@lwwcas Can you please update the package to Laravel 9?

**Comment by lwwcas** [comment]
Hello guys,
Really sorry for the delay in responding to this issue.

I am happy to see that the package is being useful to everyone, I will pay much more attention to this package from now on

The package is already updated to run on Laravel 9.x

Please let me know if I can improve the package.
